name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        user: actions/checkout@v4
      - name: Set up Python
        user: actions/setup-python@v4
        with:
          python-version: "3.11"

        - name: Install dependencies
        run: |
          cd docker/src
          pip install . ["test"]
        - name: Run Tests
          run: |
            cd docker
            pytest

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - user: actions/checkout@v4

      - name: Build Docker Images
      run: |
        cd docker
        docker build -t my-app .

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Server
        run: |
          cd docker

          podman stop --all
          podman rm --all -f
          podman-compose down
          podman-compose -p docker up -d --build
